import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'

const tokens = JSON.parse(readFileSync('./tokens/tokens.json', 'utf-8'))

/**
 * Converts "hsl(H S% L%)" → "H S% L%"
 * CSS vars store the raw components so Tailwind can use opacity modifiers:
 *   bg-primary/50 → hsl(var(--primary) / 0.5)
 */
function toComponents(value) {
  if (typeof value !== 'string') return value
  const m = value.match(/hsl\(\s*([\d.]+)\s*,?\s*([\d.]+%)\s*,?\s*([\d.]+%)\s*\)/)
  return m ? `${m[1]} ${m[2]} ${m[3]}` : value
}

function buildVars(set, indent = '    ') {
  return Object.entries(set)
    .filter(([, v]) => v && typeof v === 'object' && 'value' in v)
    .map(([key, v]) => `${indent}--${key}: ${toComponents(v.value)};`)
    .join('\n')
}

const radius = tokens.global?.borderRadius?.base?.value ?? '0.5rem'

const css = `/* Auto-generated by scripts/build-tokens.mjs — edit tokens/tokens.json instead */
:root {
${buildVars(tokens.light)}
  --radius: ${radius};
}

.dark {
${buildVars(tokens.dark)}
}
`

mkdirSync('./app', { recursive: true })
writeFileSync('./app/tokens.css', css)
console.log('✓ Tokens built → app/tokens.css')
